### ISSUE TITLE
We need new update code

### ISSUE THREAD

**Issue by Meganium97** [Lazr1026/Sans#32]
So right now the only thing stopping us from self-hosting the bot are:
1. The update code
2. The multiple instances of remaining /home/lucas/
Now I think what we could do it replicate Gnome's TTS bot's update code, by pulling directly from github whenever a pull is done.
However, that would need to restart the bot.
There is a solution for that as well, which is pm2, which is roughly coded.
Here's a snippet of that TTS code I was talking about:

![](https://cdn.discordapp.com/attachments/694127040814776391/778024033031159828/Screenshot_20201116-2228432.png)
We just need to figure out how to do this and that should fix self-hosting problems.

**Comment by Meganium97** [comment]
Also it would require us to change the ids of whatever ids are needed which is doable.

**Comment by Lazr1026** [comment]
It's been over a year and i believe that the code we have right now just works:tm:.
