### ISSUE TITLE
Hi it's me the Spanish Inquisition

### ISSUE THREAD

**Issue by bleck9999** [Lazr1026/Sans#8]
https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L443
Why the fuck does a discord bot need root perms?

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L470-L569
this is not ok
there's already a default help command, you can set it by putting a string at the start of the function body (like L108, the helptext for `about` is "about Kurisu" 

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L1-L8
What are you trying to achieve here? Imports aren't really doing anything worth being broken up into 'stages'. Importing `discord` and `subprocess` does nothing to init anything, it just makes the modules available.

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L108
I think you missed this when removing kurisu references.

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L10
You're already using commands.Bot, why do you do this* complete mess then? You can specify arguments in the function prototype, you don't have to slice message.content to find them.

*some examples of the complete mess referenced earlier:
https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L70
https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L148
https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L203

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L103-L104
This is not needed, you can just check if the argument(s) provided exist 

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L399
The sh files you use throughout the program (plswhy) aren't provided and it's not stated where to find them. As is this program is incomplete.

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L443
Potentially identifiable information.

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L458
Why?

https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L49
Multiline strings exist, just surround the text block with either `"""` or `'''`

A few miscellaneous other points, [Kurisu](https://github.com/nh-server/kurisu) is licensed under the apache 2.0 license, meaning you need to provide a copy of the apache license with this code (given that you have most definitely used code from Kurisu) oh and INPUT SANITISATION. USE IT.

**Comment by Lazr1026** [comment]
i cant give 2 shit, its the way i do it, not you

**Comment by kriegisrei** [comment]
> 
> 
> i cant give 2 shit, its the way i do it, not you

wow bro dont be an asshole no one likes an asshole bro

**Comment by Lazr1026** [comment]
ok, this is just funny to me

**Comment by Lazr1026** [comment]
actually reading through it i uhh see what i should do, thamk

**Comment by Lazr1026** [comment]
how do i uhh put an apache license, i honestly dont know :p

**Comment by ItsPizzaTime1501** [comment]
http://www.apache.org/licenses/LICENSE-2.0.txt @Lazr1026 i think you can do it by just adding this txt file to the repo as `LICENSE.txt` or you could merge #10

**Comment by techmuse8** [comment]
> https://github.com/Lazr1026/Sans/blob/88b40af745ccf6f881f501431e4ce99786d5ecee/sans.py#L443
> 
> 
> Why the fuck does a discord bot need root perms?

.ctl update command so you won't have to sudo

**Comment by viridivn** [comment]
I will be moving all of the bash script related things to the recovery bot, since I agree that they are pretty bad, but they also do _work_ well enough. This way, the main bot can still be semi-portable and complete, but the commands can still be used for our instance.

**Comment by viridivn** [comment]
I'm going to close this issue because most of the suggestions here have been implemented, and the remaining ones (namely, the use of sh scripts throughout) have been improved on a little, and I plan to fully get rid of them in the future.
